config/routes.rb
Rails.application.routes.draw do
  resources :channels
  resources :discussions
  #devise_for :users
  namespace :admin do
      resources :dbcorsos, :materia, :corso_materia


      root to: "dbcorsos#index"
    end
  root 'pages#home'
  get  'vita/alloggio'     => 'vita#alloggio'
  get  'vita/citta'        => 'vita#citta'
  get  'vita/viaggio'      => 'vita#viaggio'
  get  'vita/associazioni' => 'vita#associazioni'
  get  'vita/divertimento' => 'vita#divertimento'
  get  'corsi'             => 'pages#corsi'
  get  'corsi/corso/:id'   => 'pages#corso'
  get  'tags/corsi/corso/:id'   => 'pages#corso'
  get  'dipartimento'             => 'pages#dipartimento'
  get  'materia/:id' => 'pages#materia'
  get  'tags/:tag', to: 'pages#corsi', as: :tag
  get  'discussions' => 'discussions#index'

  resources :channels
  resources :discussions do
    resources :replies
  end


  devise_for :users, controllers: { registrations: 'registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/partials/_footer.html.erb
<footer style="color: #696969;" id=main-footer class="text-center" class="navbar-brand">
	<p> Built by ingeger students Wilfried Ndomo and Rosine Tsamo <br>
		 [realized for the course 'progetto di
	programmazione concorente' at University of studys of Ferrara A.Y 2017/2018]
	</p>
	 © 2018 All Rigth Reserved.
</footer>

app/views/layouts/partials/_nav.html.erb
<script type="text/javascript">
$('.dropdown').hover(function(){
   $('.dropdown-menu', this).stop(true, false).slideToggle();   
   $(this).toggleClass('open');
});


</script>
<hr>
<nav style="color: #696969;" class="">
	<div class="col-4 text-left">
            <p class="text-nowrap"><%= Time.now.asctime %></p> 
     </div>

</nav>



<%= render 'layouts/partials/nav_discussions' %>


<nav style="color: #696969;" class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" <%= link_to "Home", root_path %> </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Il dipartimento", dipartimento_path %> <span class="sr-only">(current)</span></a>
      </li>
      
      <li class="nav-item ">
        <a class="nav-link" <%= link_to "Tutti i Corsi", corsi_path %> <span class="sr-only">(current)</span></a>
      </li>     

      <li class="nav-item dropdown" >
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="false" aria-expanded="false">
          vita a Ferrara
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" <%= link_to "viaggio", vita_viaggio_path %></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" <%= link_to "alloggio", vita_alloggio_path %></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" <%= link_to "associazioni", vita_associazioni_path %></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" <%= link_to "divertimento", vita_divertimento_path %></a>
          
        </div>
      </li>
      <!--li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li-->
    </ul>
    


    <%= form_tag(corsi_path, method: :get) do %>
    
    <input placeholder="Interessi" <%= text_field_tag :term, params[:term] %>

    <input placeholder="Sbocchi" <%= text_field_tag :term2, params[:term2] %>
    <%= submit_tag 'Search', name: nil %>
    <% end %>

    



  </div>
</nav>

app/views/layouts/partials/_nav_discussions.html.erb
<% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

    
     <nav class="navbar is-light" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to discussions_path, class:"navbar-item" do %>
          <h1 class="title is-5">Discussions</h1>
        <% end  %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <% if user_signed_in? %>
          <div class="navbar-item">
            <div class="field is-grouped">
              <%= link_to 'New Discussion', new_discussion_path, class:"button is-info" %>
            </div>
          </div>
          <div class="navbar-item has-dropdown is-hoverable">
            <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
            <div class="navbar-dropdown is-right">
              <%= link_to current_user.username, edit_user_registration_path, class:"navbar-item" %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
            </div>
          </div>
         <% else %>
         <div class="navbar-item">
          <div class="field is-grouped">

            <p class="control">
              <%= link_to 'New Discussion', new_discussion_path, class:"button is-info" %>
            </p>

            <p class="control">

            	

              <%= link_to "Sign In", new_user_session_path, class: "button is-light"%>
            </p>

            <p class="control">
              <%= link_to "Sign up", new_user_registration_path, class: "button is-light" %>
            </p>
          </div>
          </div>
          <% end %>

        </div>
    </div>
  </nav>